deploy:
  provider: heroku
  api_key:
    secure: gzZlpRdOfkwzskvE5FnPhntWyKsOQvlCDXnLRMrtNcZBJsz54r9yhwAyrczQppKiqXQS6/9PxPtsPc3JP4p4HbR5mEMV7WrxHvDkJMwjXrgdymvec+DV/xtyZXL19/36Ad0FK46MlF0Av6/IHmCYj5FVh9ZpszZwwURq7dDKC179DXn1GByFtkj0tlx942rcLAjzqsQRrgTgNh0+tTvga6YKOz0R9nNvEf0Fv81AVHOWNo//qvj1ywfuQQl0jDhXeaFm2Pc72yEmhFUuGeZAlzyyZh9RgCNy1L+j3X8rg7J3CvLtM3vE5Nl0WhQxidfQKpsERfnnfymN4oNd9NPdnGgnsKel0ncQ4FJFgGGowndrU9wCsKOfBNICCZyUo80PK1m2ELoNs//5U+frOD4osLcJHSHpOb1X2EliZxPQzo36G9QjoBMlm2Eb2aGFjwDWTwAiTx524fRx0RovxAr466zwD3B5YO688Isfl4lATQ/ZouW4y92uIYBZq0BeB7LnvAlKXWMhd6DuyKjnCjzYbgafea6O080RpsfLjmi2u1zAC+hFFhm6XE5iojlXIZDEi2YBjMSUaworVwnV3efN27uf6RO9AcLRHL/8+zwzEN19UQ0N43OHF/YXo0wuG06OaZymKWeLiu10a4mOOzLg2W487oAuAntcMlORrig57iw=
  app: 'quick-tutor-qtie5'
  on:
    repo: uva-cs3240-s20/project-103-qtie5
