services:
  - postgresql
language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
before_script:
- psql postgres -c "CREATE USER qtie5 WITH PASSWORD 'password';"
- psql postgres -c "CREATE DATABASE quicktutordb WITH OWNER qtie5;"
- psql postgres -c "ALTER USER qtie5 SUPERUSER CREATEROLE CREATEDB REPLICATION;"
- python manage.py makemigrations
- python manage.py migrate
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: BpUayzu0bOmuhyzM3rqhiweNDKQbwi5XV0NFmeJIso/ZyYSwWGHFPk5Ts9sOrxz9DW3VEXSNFrvHWZH5+QU/sprxkFsapfLtC9XUNkmpvTxB1CXQwIshlKaM+q4kDH9Xbca/Wv2pJPkb/nau+TQITAAAtMCVMOHLmQitUKp8kdja8Plvog8yRvVOyqkg+7dui/cNkci13PAoZzWtfzit+cymu3ZFJIh5a8a4Agy9zY2zEkxci6uN1ft4naK3bw25dmJ/Gq+B9i3oneCtJJUrmwUuVSpgdVh/xOH3dUpN5cv/tBAvV3OXQ0kMV6rFyMjcovUzNErY3DQKUrPqhfX82cuKIt+n9jammAsxzSNHiiQGSPqecfAxrKzpEi3CAAYpgtMT4TgMHKz7la1Heqsh5PL+laPDe8M9b2F/NtqtMh/MSISuqNETsWMQsCRU3vJfrofnIni4+2LVFZ23sb9ieJSEYAF1tE0mS65co6ySS9Raib0YzaXcPb5nxQ1esMTDVXiC6kdu5AU6/iplu3/H7t6C4vzBe24Hyy/D6XvQkjtriotO+rIPRaM+UNmaBug5d82kDIMe8PKorRcIFvQfA9wYdFSWvi2PG8CMnQCky0v3GiKo0aDKktcO0Nz8UBxrP5lh6ag7tG3FktpzuMbU0yfaBn8hq8sjSQvJgmGnWJY=
  app: quick-tutor-qtie5
