services:
  - postgresql
language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
before_script:
- psql postgres -c "CREATE USER qtie5 WITH PASSWORD 'password';"
- psql postgres -c "CREATE DATABASE quicktutordb WITH OWNER qtie5;"
- psql postgres -c "ALTER USER qtie5 SUPERUSER CREATEROLE CREATEDB REPLICATION;"
- python manage.py makemigrations
- python manage.py migrate
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: JRoCfxZ4MltEaBTp0w0H1cODBdly5hnxOfSJtn56139Lt+3Q9FYvVfig0IFqFrhM0WnrvQEUTmGyytKQpTtqAn7VR338qi8na/KcF7g1nIOlW/LhbKWXyexmKZC1cnXPGnJNZK0ml5aWU1U+LOyCYuh8Whu+cn/lwkiAYbyRAIALFQ4H9WnaWhTopFFKTFXR4uV1tCeaZfgRg9qknAUS4ErIHELM7cs6E3nFI8POoL+S7xmpMfwsRSTsZe6kI34SVeXPykVCIR+YFbfR4MBlKJcwP2031Gb9hl9Bvnlp/YsZvh3QTMQi9n57aepTlnrP5rZxWoi7rCLUbbh+gvMci8ySsh1lo2Qoe9a0X2gv6gT466Y1kPuTCC0EnJRTDVAqAsXNiCdLxUHo16EezcftvlNnF+1JQhKJrfjZWUu+eFVElK+aAVqIpZFnVKpKktQIGs5y0seb6ov/jKlLUnbiF/LpPRJ6utfo5aH7trqY6glpaLjQiHPkTVOSi7IybgjtyP7VxRQawey8sVpl6vjbUpHT8ZGUNj8HXW5omNAhgFxhl+8xrqNr3sL0iKDBRUAH4+rOM8UJckQGNT0xy7tBA8f4j0kurAZb7m/TA0HjNj05pMe7kxR78vafMKh35++vEqDyXSICAJa8BrsczeRLFew1fmyLPuqmD40n8WEBfj4=
  app: quick-tutor-qtie5
