services:
  - postgresql
language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
before_script:
- psql postgres -c "CREATE USER qtie5 WITH PASSWORD 'password';"
- psql postgres -c "CREATE DATABASE quicktutordb WITH OWNER qtie5;"
- psql postgres -c "ALTER USER qtie5 SUPERUSER CREATEROLE CREATEDB REPLICATION;"
- python manage.py makemigrations
- python manage.py migrate
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: iBkzIkX4nIsZyeuN/uiwpi6uctdTjRYQuk/tOuIq9jMAtSWLSZwjx8hGl2fbjIEpQCuPKfzBPe+Krv4WlwnNB+tufCflP1Dvlpl0QFgl9JwBG0OuBFZkUkvpHZyvlNE9+IIF+CJtNeA/jFTMQyXRNPN3fGFpQOOm5m3BStWKT1/MRJiGg1mx0uPqlkgsfob8BR4932SfMC9QloKqMdkBDp+B6ywahAODfAkpxAPJbrZ8qCppwTZe6vQzdnGdJODFuJkGQXPC9OM/3S7Pi9u1R+5YV5jWS9jSnjUPQI9pEgiM4viBg5+mxTCgWoQzPrT+axtYUhmSccprxEnskHdjPKq6wXe7fW9Zaiq0vlCl68VKnKgrWHRmjwGvYHKRXMAKV1SJgCkrkm0vZ2swNJx1rC/RhCIhmC0OadY2z1OipC7Hv7X18sSD9yuZNIHDo/rpvapjK5JTJ6ix6B92HkABcYRY6MhMiVqxsMQj0UdLPOXWSXBPrcdwBNQcnh/+cNs8UC33aV5yv4RWXnBZTjRRAPsnBbQsxiFHSLk/yMdlHenxjXplYe3y4n+9rp8evydEWspHtrxOEFuZXoZL+843yfHpAkuFv0ElITYTxsSekO91evpIXkvJySG5D4y58gDDd/V5qvvLqfwuNDNrOb8GFFCxAGVAK4asRYsD1Jdx9Dk=
  app: project-103-qtie5
  on:
    repo: uva-cs3240-s20/project-103-qtie5
