# Generated by Django 3.0.2 on 2020-03-28 14:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0002_auto_20200322_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 15, 49, 20, 975005, tzinfo=utc)),
        ),
    ]
